# Generated by Django 5.2.5 on 2025-08-30 14:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='KahootGeneratorPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('default_questions_count', models.IntegerField(default=10, help_text='Nombre de questions par défaut')),
                ('default_timer_enabled', models.BooleanField(default=True, help_text='Chrono activé par défaut')),
                ('default_timer_duration', models.IntegerField(default=30, help_text='Durée par défaut en secondes')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='KahootSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('questions_count', models.IntegerField(default=10)),
                ('timer_enabled', models.BooleanField(default=True)),
                ('timer_duration', models.IntegerField(default=30)),
                ('selected_chapters', models.JSONField(default=list)),
                ('questions_data', models.JSONField(default=list)),
                ('current_question_index', models.IntegerField(default=0)),
                ('participants', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Session Kahoot',
                'verbose_name_plural': 'Sessions Kahoot',
            },
        ),
    ]
