# Generated by Django 5.2.5 on 2025-08-30 16:34

from django.db import migrations, models
import random
import string


def generate_short_codes(apps, schema_editor):
    """Génère des codes courts pour les sessions existantes"""
    KahootSession = apps.get_model('kahoot', 'KahootSession')
    
    for session in KahootSession.objects.all():
        if not session.short_code:
            # Générer un code unique
            while True:
                code = ''.join(random.choices(string.ascii_uppercase + string.digits, k=8))
                if not KahootSession.objects.filter(short_code=code).exists():
                    session.short_code = code
                    session.save()
                    break


class Migration(migrations.Migration):

    dependencies = [
        ('kahoot', '0001_initial'),
    ]

    operations = [
        # 1. Ajouter le champ sans contrainte unique
        migrations.AddField(
            model_name='kahootsession',
            name='short_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        
        # 2. Générer les codes pour les sessions existantes
        migrations.RunPython(generate_short_codes),
        
        # 3. Rendre le champ non-null et unique
        migrations.AlterField(
            model_name='kahootsession',
            name='short_code',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
