# Generated by Django 5.2.5 on 2025-08-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kahoot', '0002_kahootsession_short_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kahootsession',
            name='short_code',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
