# Generated by Django 5.2.5 on 2025-08-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kahoot', '0003_alter_kahootsession_short_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='kahootsession',
            name='participant_answers',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='kahootsession',
            name='participant_scores',
            field=models.JSONField(default=dict),
        ),
    ]
