# Generated by Django 5.2.5 on 2025-08-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kahoot', '0004_kahootsession_participant_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kahootsession',
            name='answers_revealed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kahootsession',
            name='current_phase',
            field=models.CharField(default='waiting', max_length=20),
        ),
        migrations.AddField(
            model_name='kahootsession',
            name='question_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
