# Generated by Django 5.2.5 on 2025-08-28 20:53

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='QcmBankBPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='QcmQuestionAPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('layout', models.CharField(choices=[('text', '100% texte'), ('text_media', '67% texte / 33% média')], default='text', max_length=16)),
                ('statement', wagtail.fields.RichTextField(help_text='Énoncé (MathJax OK).')),
                ('video_url', models.URLField(blank=True)),
                ('requires_justification', models.BooleanField(default=False, help_text="Exiger une justification écrite de l'élève.")),
                ('explanation', wagtail.fields.RichTextField(blank=True, help_text='Explication globale (optionnel).')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='QcmQuestionAOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', wagtail.fields.RichTextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('explanation', wagtail.fields.RichTextField(blank=True, help_text='Explication affichée après validation (optionnel).')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='qcm.qcmquestionapage')),
            ],
            options={
                'verbose_name': 'Proposition',
                'verbose_name_plural': 'Propositions',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QcmVariantB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('layout', models.CharField(choices=[('text', '100% texte'), ('text_media', '67% texte / 33% média')], default='text', max_length=16)),
                ('statement', wagtail.fields.RichTextField(help_text='Énoncé (MathJax OK).')),
                ('answer', wagtail.fields.RichTextField(help_text='Réponse correcte.')),
                ('explanation', wagtail.fields.RichTextField(blank=True, help_text='Explication optionnelle.')),
                ('video_url', models.URLField(blank=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='qcm.qcmbankbpage')),
            ],
            options={
                'verbose_name': 'Variante',
                'verbose_name_plural': 'Variantes',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
