# Generated by Django 5.2.5 on 2025-08-28 21:38

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcmquestionaoption',
            name='explanation',
            field=wagtail.fields.RichTextField(blank=True, default='', null=True),
        ),
    ]
