# Generated by Django 5.2.5 on 2025-08-29 17:24

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0002_alter_qcmquestionaoption_explanation'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='QcmQuestionCPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('layout', models.CharField(choices=[('text', '100% texte'), ('text_media', '67% texte / 33% média')], default='text', max_length=16)),
                ('statement', wagtail.fields.RichTextField(help_text='Énoncé (MathJax OK).')),
                ('video_url', models.URLField(blank=True)),
                ('correct_answers', models.TextField(help_text="Liste des bonnes réponses séparées par ';' (texte et/ou LaTeX/MathJax)")),
                ('incorrect_answers', models.TextField(help_text="Liste des mauvaises réponses séparées par ';' (texte et/ou LaTeX/MathJax)")),
                ('requires_justification', models.BooleanField(default=False, help_text="Exiger une justification écrite de l'élève.")),
                ('explanation', wagtail.fields.RichTextField(blank=True, help_text='Explication globale (optionnel).')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
