# Generated by Django 5.2.5 on 2025-08-29 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0003_qcmquestioncpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qcmquestionaoption',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='qcmvariantb',
            name='explanation',
        ),
    ]
