# Generated by Django 5.2.5 on 2025-08-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0004_remove_qcmquestionaoption_explanation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qcmquestionapage',
            name='requires_justification',
        ),
        migrations.RemoveField(
            model_name='qcmquestioncpage',
            name='requires_justification',
        ),
        migrations.AddField(
            model_name='qcmbankbpage',
            name='sans_redaction',
            field=models.BooleanField(default=True, help_text='QCM sans rédaction (cochez pour QCM simple, décochez pour QCM avec justification écrite)'),
        ),
        migrations.AddField(
            model_name='qcmquestionapage',
            name='sans_redaction',
            field=models.BooleanField(default=True, help_text='QCM sans rédaction (cochez pour QCM simple, décochez pour QCM avec justification écrite)'),
        ),
        migrations.AddField(
            model_name='qcmquestioncpage',
            name='sans_redaction',
            field=models.BooleanField(default=True, help_text='QCM sans rédaction (cochez pour QCM simple, décochez pour QCM avec justification écrite)'),
        ),
    ]
