# Generated by Django 5.2.5 on 2025-09-02 01:40

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0005_remove_qcmquestionapage_requires_justification_and_more'),
        ('referentiel', '0003_categoriemethode'),
    ]

    operations = [
        migrations.CreateModel(
            name='QcmQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FC', 'Flashcard')], default='FC', max_length=2)),
                ('question', wagtail.fields.RichTextField(help_text='Question de la flashcard (MathJax OK).')),
                ('answer', wagtail.fields.RichTextField(help_text='Réponse de la flashcard (MathJax OK).')),
                ('explanation', wagtail.fields.RichTextField(blank=True, help_text='Explication optionnelle.')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qcm_questions', to='referentiel.chapitre', verbose_name='Chapitre')),
            ],
            options={
                'verbose_name': 'Question FC',
                'verbose_name_plural': 'Questions FC',
                'ordering': ['chapitre', 'id'],
            },
        ),
    ]
