# Generated by Django 5.2.5 on 2025-09-02 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0006_qcmquestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QcmQuestion',
        ),
    ]
