# Generated by Django 5.2.5 on 2025-09-07 09:17

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0007_delete_qcmquestion'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qcmquestionapage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='qcmquestionapage',
            name='layout',
        ),
        migrations.RemoveField(
            model_name='qcmquestionapage',
            name='statement',
        ),
        migrations.RemoveField(
            model_name='qcmquestionapage',
            name='video_url',
        ),
        migrations.CreateModel(
            name='QcmQuestionAStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('layout', models.CharField(choices=[('text', '100% texte'), ('text_media', '67% texte / 33% média')], default='text', max_length=16)),
                ('statement', wagtail.fields.RichTextField(help_text='Énoncé (MathJax OK).')),
                ('video_url', models.URLField(blank=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='qcm.qcmquestionapage')),
            ],
            options={
                'verbose_name': 'Énoncé',
                'verbose_name_plural': 'Énoncés',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
