# Generated by Django 5.2.5 on 2025-09-01 20:34

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Introduction')),
                ('body', wagtail.fields.StreamField([('rich_text', 0), ('section', 16)], blank=True, block_lookup={0: ('methode.blocks.StyledRichTextBlock', (), {}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('50_50', '50/50'), ('70_30', '70/30'), ('30_70', '30/70'), ('33_33_33', '33/33/33'), ('100_50_50', '100/50/50')], 'label': 'Disposition'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image', 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Légende', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3)]], {}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('c', 'C'), ('cpp', 'C++'), ('bash', 'Bash'), ('markup', 'HTML'), ('css', 'CSS')], 'label': 'Langage'}), 6: ('wagtail.blocks.TextBlock', (), {'label': 'Code'}), 7: ('wagtail.blocks.StructBlock', [[('language', 5), ('code', 6)]], {}), 8: ('wagtail.contrib.table_block.blocks.TableBlock', (), {}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Titre', 'required': True}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image', 'required': False}), 11: ('wagtail.blocks.RichTextBlock', (), {'label': 'Texte', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('title', 9), ('image', 10), ('text', 11)]], {}), 13: ('wagtail.blocks.StreamBlock', [[('rich_text', 0), ('image', 4), ('code', 7), ('table', 8), ('card', 12)]], {'required': False}), 14: ('wagtail.blocks.StreamBlock', [[('rich_text', 0), ('image', 4), ('code', 7), ('table', 8), ('card', 12)]], {'help_text': 'Troisième colonne pour 33/33/33 et 100/50/50', 'required': False}), 15: ('wagtail.blocks.URLBlock', (), {'label': 'URL vidéo', 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('layout', 1), ('left', 13), ('right', 13), ('extra', 14), ('video_url', 15)]], {})}, verbose_name='Contenu')),
            ],
            options={
                'verbose_name': 'Méthode',
                'verbose_name_plural': 'Méthodes',
            },
            bases=('wagtailcore.page',),
        ),
    ]
