# Generated by Django 5.2.5 on 2025-09-01 20:58

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methode', '0001_initial'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodeHubPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Introduction')),
            ],
            options={
                'verbose_name': 'Hub Méthodes',
                'verbose_name_plural': 'Hub Méthodes',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='methodepage',
            name='body',
            field=wagtail.fields.StreamField([('paragraphe', 3), ('titre', 6), ('image', 9), ('code', 12), ('card', 16), ('tableau', 17), ('section_2cols', 22), ('section_3cols', 26), ('section_wide_left', 30)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('normal', 'Normal'), ('etape', 'Étape avec titre'), ('protocole', 'Protocole'), ('exemple', 'Exemple'), ('methode', 'Méthode')], 'label': 'Style'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'underline', 'link', 'superscript', 'subscript', 'strikethrough', 'ol', 'ul', 'hr', 'blockquote', 'code', 'image', 'embed'], 'label': 'Contenu'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Titre (pour étape/exemple/méthode)', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('style', 0), ('contenu', 1), ('titre', 2)]], {}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h1', 'H1'), ('h2', 'H2'), ('h3', 'H3')], 'label': 'Niveau'}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Texte'}), 6: ('wagtail.blocks.StructBlock', [[('niveau', 4), ('texte', 5)]], {}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image', 'required': True}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Légende', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('image', 7), ('caption', 8)]], {}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('c', 'C'), ('cpp', 'C++'), ('java', 'Java'), ('php', 'PHP'), ('sql', 'SQL'), ('bash', 'Bash')], 'label': 'Langage'}), 11: ('wagtail.blocks.TextBlock', (), {'label': 'Code'}), 12: ('wagtail.blocks.StructBlock', [[('langage', 10), ('code', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'label': 'Titre', 'required': True}), 14: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image', 'required': False}), 15: ('wagtail.blocks.RichTextBlock', (), {'label': 'Texte', 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('title', 13), ('image', 14), ('text', 15)]], {}), 17: ('wagtail.contrib.table_block.blocks.TableBlock', (), {}), 18: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('50-50', '50 / 50'), ('70-30', '70 / 30'), ('30-70', '30 / 70')], 'label': 'Disposition'}), 19: ('wagtail.blocks.StreamBlock', [[('paragraphe', 3), ('titre', 6), ('image', 9), ('code', 12), ('card', 16), ('tableau', 17)]], {'label': 'Colonne gauche', 'required': False}), 20: ('wagtail.blocks.StreamBlock', [[('paragraphe', 3), ('titre', 6), ('image', 9), ('code', 12), ('card', 16), ('tableau', 17)]], {'label': 'Colonne droite', 'required': False}), 21: ('wagtail.blocks.URLBlock', (), {'label': 'URL vidéo', 'required': False}), 22: ('wagtail.blocks.StructBlock', [[('ratio', 18), ('left', 19), ('right', 20), ('video_url', 21)]], {}), 23: ('wagtail.blocks.StreamBlock', [[('paragraphe', 3), ('titre', 6), ('image', 9), ('code', 12), ('card', 16), ('tableau', 17)]], {'label': 'Colonne 1', 'required': False}), 24: ('wagtail.blocks.StreamBlock', [[('paragraphe', 3), ('titre', 6), ('image', 9), ('code', 12), ('card', 16), ('tableau', 17)]], {'label': 'Colonne 2', 'required': False}), 25: ('wagtail.blocks.StreamBlock', [[('paragraphe', 3), ('titre', 6), ('image', 9), ('code', 12), ('card', 16), ('tableau', 17)]], {'label': 'Colonne 3', 'required': False}), 26: ('wagtail.blocks.StructBlock', [[('col1', 23), ('col2', 24), ('col3', 25), ('video_url', 21)]], {}), 27: ('wagtail.blocks.StreamBlock', [[('paragraphe', 3), ('titre', 6), ('image', 9), ('code', 12), ('card', 16), ('tableau', 17)]], {'label': 'Colonne gauche (large)', 'required': False}), 28: ('wagtail.blocks.StreamBlock', [[('paragraphe', 3), ('titre', 6), ('image', 9), ('code', 12), ('card', 16), ('tableau', 17)]], {'label': 'Colonne droite haute', 'required': False}), 29: ('wagtail.blocks.StreamBlock', [[('paragraphe', 3), ('titre', 6), ('image', 9), ('code', 12), ('card', 16), ('tableau', 17)]], {'label': 'Colonne droite basse', 'required': False}), 30: ('wagtail.blocks.StructBlock', [[('left', 27), ('right_top', 28), ('right_bottom', 29), ('video_url', 21)]], {})}, verbose_name='Contenu'),
        ),
    ]
