# Generated by Django 5.2.5 on 2025-09-02 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methode', '0003_alter_methodepage_body'),
        ('referentiel', '0003_categoriemethode'),
    ]

    operations = [
        migrations.AddField(
            model_name='methodepage',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='referentiel.categoriemethode', verbose_name='Catégorie méthode'),
        ),
        migrations.AddField(
            model_name='methodepage',
            name='fiche_college',
            field=models.BooleanField(default=False, verbose_name='Fiche méthode collège'),
        ),
        migrations.AddField(
            model_name='methodepage',
            name='fiche_lycee',
            field=models.BooleanField(default=False, verbose_name='Fiche méthode lycée'),
        ),
    ]
