# Generated by Django 5.2.5 on 2025-09-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methode', '0004_methodepage_categorie_methodepage_fiche_college_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='methodehubpage',
            options={'verbose_name': 'Recensement Fiches Méthode', 'verbose_name_plural': 'Recensement Fiches Méthode'},
        ),
        migrations.AddField(
            model_name='methodehubpage',
            name='onglet_actif',
            field=models.CharField(choices=[('college', 'Collège'), ('lycee', 'Lycée')], default='college', max_length=10, verbose_name='Onglet actif par défaut'),
        ),
    ]
