# Generated by Django 5.2.5 on 2025-09-06 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0002_alter_flashcarditem_sort_order'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardsetpage',
            name='source_file',
            field=models.ForeignKey(blank=True, help_text="CSV (UTF-8 ; ou ,) avec entêtes question,answer[,tags,video_url] ou TXT avec lignes 'question|||answer|||tags' (tags optionnel).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
    ]
