# Generated by Django 5.2.5 on 2025-09-06 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0003_alter_flashcardsetpage_source_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcardsetpage',
            name='mode_creation',
        ),
    ]
