# Generated by Django 5.2.5 on 2025-09-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0004_remove_mode_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardsetpage',
            name='mode_creation',
            field=models.CharField(choices=[('manual', 'Saisie manuelle'), ('import', 'Import fichier (CSV / TXT)')], default='manual', max_length=10),
        ),
    ]
