# Generated by Django 5.2.5 on 2025-09-06 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0005_add_mode_creation_back'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcardsetpage',
            name='mode_creation',
        ),
    ]
