# Generated by Django 5.2.5 on 2025-09-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0006_remove_flashcardsetpage_mode_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardsetpage',
            name='auto_import_on_publish',
            field=models.BooleanField(default=True, help_text='Importer automatiquement à la publication.'),
        ),
        migrations.AddField(
            model_name='flashcardsetpage',
            name='last_import_checksum',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='flashcardsetpage',
            name='last_import_document_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
