# Generated by Django 5.2.5 on 2025-08-31 20:58

import django.db.models.deletion
import modelcluster.fields
import taggit.managers
import wagtail.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExoHubPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Hub des exercices',
                'verbose_name_plural': 'Hubs des exercices',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ExoPageSimple',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=2, verbose_name='Difficulté')),
                ('estimated_time_min', models.PositiveIntegerField(default=10, verbose_name='Temps estimé (minutes)')),
                ('total_points', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Total des points')),
                ('family_id', models.CharField(blank=True, max_length=64, verbose_name='ID de famille')),
                ('sections', wagtail.fields.StreamField([('s100', 9), ('s50_50', 12), ('s70_30', 15)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'underline', 'link', 'h2', 'h3', 'h4', 'ol', 'ul', 'code', 'blockquote', 'superscript', 'subscript'], 'label': 'Texte riche'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Légende', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2)]], {'label': 'Image'}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('c', 'C'), ('cpp', 'C++'), ('java', 'Java'), ('php', 'PHP'), ('sql', 'SQL'), ('bash', 'Bash'), ('json', 'JSON'), ('xml', 'XML'), ('yaml', 'YAML'), ('markdown', 'Markdown')], 'label': 'Langage'}), 5: ('wagtail.blocks.TextBlock', (), {'label': 'Code'}), 6: ('wagtail.blocks.StructBlock', [[('language', 4), ('source', 5)]], {'label': 'Code'}), 7: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': 'Tableau'}), 8: ('wagtail.blocks.StreamBlock', [[('rich_text', 0), ('image', 3), ('code', 6), ('table', 7)]], {'label': 'Contenu'}), 9: ('wagtail.blocks.StructBlock', [[('content', 8)]], {}), 10: ('wagtail.blocks.StreamBlock', [[('rich_text', 0), ('image', 3), ('code', 6), ('table', 7)]], {'label': 'Colonne gauche'}), 11: ('wagtail.blocks.StreamBlock', [[('rich_text', 0), ('image', 3), ('code', 6), ('table', 7)]], {'label': 'Colonne droite'}), 12: ('wagtail.blocks.StructBlock', [[('left', 10), ('right', 11)]], {}), 13: ('wagtail.blocks.StreamBlock', [[('rich_text', 0), ('image', 3), ('code', 6), ('table', 7)]], {'label': 'Colonne gauche (70%)'}), 14: ('wagtail.blocks.StreamBlock', [[('rich_text', 0), ('image', 3), ('code', 6), ('table', 7)]], {'label': 'Colonne droite (30%)'}), 15: ('wagtail.blocks.StructBlock', [[('left', 13), ('right', 14)]], {})}, verbose_name="Sections de l'énoncé")),
                ('questions', wagtail.fields.StreamField([('question', 12)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'underline', 'link', 'h2', 'h3', 'h4', 'ol', 'ul', 'code', 'blockquote', 'superscript', 'subscript'], 'label': 'Texte riche'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Légende', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2)]], {'label': 'Image'}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('c', 'C'), ('cpp', 'C++'), ('java', 'Java'), ('php', 'PHP'), ('sql', 'SQL'), ('bash', 'Bash'), ('json', 'JSON'), ('xml', 'XML'), ('yaml', 'YAML'), ('markdown', 'Markdown')], 'label': 'Langage'}), 5: ('wagtail.blocks.TextBlock', (), {'label': 'Code'}), 6: ('wagtail.blocks.StructBlock', [[('language', 4), ('source', 5)]], {'label': 'Code'}), 7: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': 'Tableau'}), 8: ('wagtail.blocks.StreamBlock', [[('rich_text', 0), ('image', 3), ('code', 6), ('table', 7)]], {'label': 'Contenu de la question'}), 9: ('wagtail.blocks.DecimalBlock', (), {'decimal_places': 2, 'default': Decimal('0.00'), 'help_text': 'ex : 0.25 (affiché 0,25)', 'label': 'Points', 'max_digits': 5}), 10: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Flashcard', 'label': 'Question Flashcard', 'required': False}), 11: ('wagtail.blocks.StreamBlock', [[('rich_text', 0), ('image', 3), ('code', 6), ('table', 7)]], {'label': 'Solution', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('content', 8), ('points', 9), ('fc', 10), ('solution', 11)]], {})}, verbose_name='Questions')),
            ],
            options={
                'verbose_name': 'Exercice simple',
                'verbose_name_plural': 'Exercices simples',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ExoPageSimpleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='exo.exopagesimple')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='exopagesimple',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='exo.ExoPageSimpleTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
