# Generated by Django 5.2.5 on 2025-08-31 22:54

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exo', '0002_remove_exopagesimple_questions_and_more'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametreExoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('sync_variant_count', models.PositiveIntegerField(default=5, verbose_name='Nombre de variantes synchronisées (K)')),
                ('sync_seed', models.CharField(blank=True, max_length=100, verbose_name='Seed pour index synchronisé (optionnel)')),
                ('free_seed', models.CharField(blank=True, max_length=100, verbose_name='Seed pour tirages non cochés (optionnel)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
            ],
            options={
                'verbose_name': "Page de paramétrage d'exercice",
                'verbose_name_plural': "Pages de paramétrage d'exercices",
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ParamItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du paramètre')),
                ('kind', models.CharField(choices=[('value', 'Valeur simple'), ('slot', 'Slot de texte'), ('image_override', "Remplacement d'image"), ('range', 'Plage numérique'), ('set', 'Ensemble de valeurs'), ('const', 'Valeur constante'), ('expr', 'Expression')], default='value', max_length=20, verbose_name='Type de paramètre')),
                ('sync_enabled', models.BooleanField(default=False, verbose_name='Synchroniser avec les autres')),
                ('range_min', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Minimum')),
                ('range_max', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Maximum')),
                ('range_step', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Pas')),
                ('set_values', models.JSONField(blank=True, null=True, verbose_name='Ensemble de valeurs')),
                ('const_value', models.TextField(blank=True, verbose_name='Valeur constante')),
                ('expr_code', models.TextField(blank=True, verbose_name="Code d'expression")),
                ('slot_default', wagtail.fields.RichTextField(blank=True, verbose_name='Texte par défaut du slot')),
                ('image_default', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image', verbose_name='Image par défaut')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='param_items', to='exo.parametreexopage')),
            ],
            options={
                'verbose_name': 'Paramètre',
                'verbose_name_plural': 'Paramètres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ParamSyncEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(verbose_name='Index (1..K)')),
                ('value_text', models.TextField(blank=True, verbose_name='Valeur texte')),
                ('value_number', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Valeur numérique')),
                ('value_richtext', wagtail.fields.RichTextField(blank=True, verbose_name='Valeur texte riche')),
                ('param_item', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_entries', to='exo.paramitem')),
                ('value_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image', verbose_name='Valeur image')),
            ],
            options={
                'verbose_name': 'Entrée synchronisée',
                'verbose_name_plural': 'Entrées synchronisées',
                'ordering': ['index'],
            },
        ),
    ]
