# Generated by Django 5.2.5 on 2025-08-31 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exo', '0003_parametreexopage_paramitem_paramsyncentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramitem',
            name='is_orphaned',
            field=models.BooleanField(default=False, verbose_name='Paramètre orphelin'),
        ),
    ]
