# Generated by Django 5.2.5 on 2025-09-01 06:52

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exo', '0004_paramitem_is_orphaned'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paramitem',
            name='image_default',
        ),
        migrations.RemoveField(
            model_name='paramitem',
            name='set_values',
        ),
        migrations.AddField(
            model_name='paramitem',
            name='set_text',
            field=models.TextField(blank=True, help_text='Séparer par ; ou retour ligne ; nombres ou texte court (1–3 mots)', verbose_name="Texte de l'ensemble"),
        ),
        migrations.AlterField(
            model_name='paramitem',
            name='kind',
            field=models.CharField(choices=[('const', 'Constante'), ('range', 'Plage'), ('set', 'Ensemble'), ('slot', 'Slot'), ('image', 'Image'), ('expr', 'Expression')], default='const', max_length=20, verbose_name='Type de paramètre'),
        ),
        migrations.AlterField(
            model_name='paramitem',
            name='name',
            field=models.CharField(help_text='Lettres/chiffres/underscore, sans espace', max_length=10, verbose_name='Nom du paramètre'),
        ),
        migrations.CreateModel(
            name='ParamImageEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailimages.image', verbose_name='Image')),
                ('param_item', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_entries', to='exo.paramitem')),
            ],
            options={
                'verbose_name': "Entrée d'image",
                'verbose_name_plural': "Entrées d'images",
                'ordering': ['order'],
            },
        ),
    ]
