# Generated by Django 5.2.5 on 2025-09-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exo', '0005_remove_paramitem_image_default_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametreexopage',
            name='free_seed',
        ),
        migrations.RemoveField(
            model_name='parametreexopage',
            name='sync_seed',
        ),
        migrations.RemoveField(
            model_name='parametreexopage',
            name='sync_variant_count',
        ),
        migrations.AlterField(
            model_name='paramitem',
            name='kind',
            field=models.CharField(choices=[('const', 'Constante'), ('range', 'Plage'), ('set', 'Ensemble'), ('slot', 'Slot'), ('image', 'Image'), ('expr', 'Expression')], default='const', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='paramitem',
            name='name',
            field=models.CharField(max_length=10, verbose_name='Nom du paramètre'),
        ),
        migrations.AlterField(
            model_name='paramitem',
            name='sync_enabled',
            field=models.BooleanField(default=False, verbose_name='Synchro'),
        ),
    ]
