# Generated by Django 5.2.5 on 2025-09-09 11:53

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exo', '0008_alter_exopagesimple_contenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exopagesimple',
            name='contenu',
            field=wagtail.fields.StreamField([('enonce', 9), ('s100', 9), ('s50_50', 12), ('s70_30', 15), ('s75_25', 18), ('question', 24)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'ol', 'ul', 'code', 'blockquote'], 'label': 'Texte riche'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Légende', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2)]], {'label': 'Image'}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('sql', 'SQL'), ('bash', 'Bash'), ('json', 'JSON'), ('xml', 'XML')], 'label': 'Langage'}), 5: ('wagtail.blocks.TextBlock', (), {'label': 'Code'}), 6: ('wagtail.blocks.StructBlock', [[('language', 4), ('source', 5)]], {'label': 'Code'}), 7: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': 'Tableau'}), 8: ('wagtail.blocks.StreamBlock', [[('rich_text', 0), ('image', 3), ('code', 6), ('table', 7)]], {'label': 'Contenu'}), 9: ('wagtail.blocks.StructBlock', [[('content', 8)]], {}), 10: ('wagtail.blocks.StreamBlock', [[('rich_text', 0), ('image', 3), ('code', 6), ('table', 7)]], {'label': 'Colonne gauche'}), 11: ('wagtail.blocks.StreamBlock', [[('rich_text', 0), ('image', 3), ('code', 6), ('table', 7)]], {'label': 'Colonne droite'}), 12: ('wagtail.blocks.StructBlock', [[('left', 10), ('right', 11)]], {}), 13: ('wagtail.blocks.StreamBlock', [[('rich_text', 0), ('image', 3), ('code', 6), ('table', 7)]], {'label': 'Colonne gauche (70%)'}), 14: ('wagtail.blocks.StreamBlock', [[('rich_text', 0), ('image', 3), ('code', 6), ('table', 7)]], {'label': 'Colonne droite (30%)'}), 15: ('wagtail.blocks.StructBlock', [[('left', 13), ('right', 14)]], {}), 16: ('wagtail.blocks.StreamBlock', [[('rich_text', 0), ('image', 3), ('code', 6), ('table', 7)]], {'label': 'Colonne gauche (75%)'}), 17: ('wagtail.blocks.StreamBlock', [[('rich_text', 0), ('image', 3), ('code', 6), ('table', 7)]], {'label': 'Colonne droite (25%)'}), 18: ('wagtail.blocks.StructBlock', [[('left', 16), ('right', 17)]], {}), 19: ('wagtail.blocks.CharBlock', (), {'help_text': 'Numéro libre : 1, 2, 3 ou 4.a, 4.b, etc.', 'label': 'Numéro'}), 20: ('wagtail.blocks.StreamBlock', [[('rich_text', 0), ('image', 3), ('code', 6), ('table', 7)]], {'label': 'Contenu de la question'}), 21: ('wagtail.blocks.DecimalBlock', (), {'decimal_places': 2, 'help_text': 'ex : 0.25 (affiché 0,25)', 'label': 'Points', 'max_digits': 5}), 22: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Flashcard', 'label': 'Flashcard', 'required': False}), 23: ('wagtail.blocks.StreamBlock', [[('rich_text', 0), ('image', 3), ('code', 6), ('table', 7)]], {'label': 'Solution', 'required': False}), 24: ('wagtail.blocks.StructBlock', [[('numero', 19), ('content', 20), ('points', 21), ('fc', 22), ('solution', 23)]], {})}, verbose_name="Contenu de l'exercice"),
        ),
    ]
