# Generated by Django 5.2.5 on 2025-09-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exo', '0010_alter_exopagesimple_contenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramitem',
            name='tableau_header',
            field=models.TextField(blank=True, help_text='Titres séparés par des points-virgules (;)', verbose_name='Entête'),
        ),
        migrations.AddField(
            model_name='paramitem',
            name='tableau_orientation',
            field=models.CharField(choices=[('h', 'Horizontal'), ('v', 'Vertical')], default='h', max_length=1, verbose_name='Orientation'),
        ),
        migrations.AddField(
            model_name='paramitem',
            name='tableau_rows',
            field=models.TextField(blank=True, help_text='Chaque ligne sur une nouvelle ligne, valeurs séparées par des points-virgules (;)', verbose_name='Lignes'),
        ),
        migrations.AlterField(
            model_name='paramitem',
            name='kind',
            field=models.CharField(choices=[('const', 'Constante'), ('range', 'Plage'), ('set', 'Ensemble'), ('slot', 'Slot'), ('image', 'Image'), ('tableau', 'Tableau'), ('expr', 'Expression')], default='const', max_length=20, verbose_name='Type'),
        ),
    ]
