# Generated by Django 5.2.5 on 2025-08-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveau',
            name='cycle',
            field=models.CharField(choices=[('college', 'Cycle 4'), ('lycee', 'Lycée'), ('Enseignement', 'Enseignement scientifique')], default='lycee', max_length=20),
        ),
    ]
