# Generated by Django 5.2.5 on 2025-09-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0002_alter_niveau_cycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieMethode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la catégorie')),
                ('couleur', models.CharField(default='#007bff', help_text='Code couleur hexadécimal (ex: #FF0000)', max_length=7, verbose_name='Code couleur')),
            ],
            options={
                'verbose_name': 'Catégorie fiche méthode',
                'verbose_name_plural': 'Catégories fiches méthode',
            },
        ),
    ]
