# Generated by Django 5.2.5 on 2025-09-27 22:46

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('contenu', 0)], blank=True, block_lookup={0: ('blocs.blocks.CKEditorBlock', (), {})}, default=list),
        ),
    ]
