# Generated by Django 5.2.5 on 2025-08-24 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0015_alter_coursindexpage_niveau_alter_courspage_contenu'),
        ('referentiel', '0002_alter_niveau_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courspage',
            name='chapitre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cours', to='referentiel.chapitre', verbose_name='Chapitre'),
        ),
    ]
