# Generated by Django 5.2.5 on 2025-08-24 15:00

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0016_alter_courspage_chapitre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courspage',
            name='contenu',
            field=wagtail.fields.StreamField([('paragraphe', 4), ('titre', 9), ('tableau', 10), ('code', 13)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('normal', 'Normal'), ('exemple', 'Exemple'), ('remarque', 'Remarque'), ('definition', 'Définition')], 'label': 'Style'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('gauche', 'Gauche'), ('centre', 'Centré'), ('justifie', 'Justifié'), ('droite', 'Droite')], 'label': 'Alignement'}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'underline', 'link', 'superscript', 'subscript', 'strikethrough', 'ol', 'ul', 'hr', 'blockquote', 'code', 'image', 'embed'], 'label': 'Contenu'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Titre (pour remarque/définition)', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('style', 0), ('alignement', 1), ('contenu', 2), ('titre', 3)]], {}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h1', 'H1'), ('h2', 'H2'), ('h3', 'H3')], 'label': 'Niveau'}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Texte'}), 7: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Afficher bouton fiche méthode'}), 8: ('wagtail.blocks.CharBlock', (), {'default': 'Fiche méthode', 'label': 'Texte du bouton'}), 9: ('wagtail.blocks.StructBlock', [[('niveau', 5), ('texte', 6), ('fiche_methode', 7), ('texte_bouton', 8)]], {}), 10: ('wagtail.contrib.table_block.blocks.TableBlock', (), {}), 11: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('c', 'C'), ('cpp', 'C++'), ('java', 'Java'), ('php', 'PHP'), ('sql', 'SQL'), ('bash', 'Bash'), ('json', 'JSON'), ('xml', 'XML'), ('yaml', 'YAML'), ('markdown', 'Markdown')], 'label': 'Langage'}), 12: ('wagtail.blocks.TextBlock', (), {'label': 'Code'}), 13: ('wagtail.blocks.StructBlock', [[('langage', 11), ('code', 12)]], {})}, verbose_name='Contenu'),
        ),
    ]
