# Generated by Django 5.2.5 on 2025-09-02 13:00

import django.db.models.deletion
import modelcluster.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referentiel', '0003_categoriemethode'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSBrandingSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecole_l1', models.CharField(blank=True, max_length=100, verbose_name="Ligne 1 - Nom de l'établissement")),
                ('ecole_l2', models.CharField(blank=True, max_length=100, verbose_name='Ligne 2 - Adresse')),
                ('ecole_l3', models.CharField(blank=True, max_length=100, verbose_name='Ligne 3 - Ville/Code postal')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name="Logo de l'établissement")),
            ],
            options={
                'verbose_name': 'Paramètres de marque',
                'verbose_name_plural': 'Paramètres de marque',
            },
        ),
        migrations.CreateModel(
            name='DSGeneratorPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('titre', models.CharField(default='Contrôle', max_length=200, verbose_name='Titre du devoir')),
                ('sous_titre_1', models.CharField(blank=True, max_length=200, verbose_name='Sous-titre 1 (chapitres/thèmes)')),
                ('sous_titre_2', models.CharField(blank=True, max_length=200, verbose_name='Sous-titre 2 (durée)')),
                ('bareme_global', models.IntegerField(default=20, verbose_name='Barème global')),
                ('afficher_bareme', models.BooleanField(default=True, verbose_name='Afficher le barème')),
                ('afficher_bareme_par_question', models.BooleanField(default=False, verbose_name='Afficher le barème par question')),
                ('afficher_duree_par_exercice', models.BooleanField(default=True, verbose_name='Afficher la durée par exercice')),
                ('qcm_min', models.IntegerField(default=0, verbose_name='Nombre minimum de QCM')),
                ('qcm_max', models.IntegerField(default=10, verbose_name='Nombre maximum de QCM')),
                ('points_par_qcm', models.DecimalField(choices=[(Decimal('1.0'), '1.0'), (Decimal('0.5'), '0.5')], decimal_places=1, default=Decimal('1.0'), max_digits=3, verbose_name='Points par QCM')),
                ('fc_min', models.IntegerField(default=0, verbose_name='Nombre minimum de questions-réponses')),
                ('fc_max', models.IntegerField(default=10, verbose_name='Nombre maximum de questions-réponses')),
                ('points_par_fc', models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=3, verbose_name='Points par question-réponse')),
                ('use_lvl1', models.BooleanField(default=True, verbose_name='Utiliser les exercices niveau 1')),
                ('ex_lvl1_min', models.IntegerField(default=0, verbose_name="Nombre minimum d'exercices niveau 1")),
                ('ex_lvl1_max', models.IntegerField(default=5, verbose_name="Nombre maximum d'exercices niveau 1")),
                ('use_lvl2', models.BooleanField(default=True, verbose_name='Utiliser les exercices niveau 2')),
                ('ex_lvl2_min', models.IntegerField(default=0, verbose_name="Nombre minimum d'exercices niveau 2")),
                ('ex_lvl2_max', models.IntegerField(default=5, verbose_name="Nombre maximum d'exercices niveau 2")),
                ('use_lvl3', models.BooleanField(default=True, verbose_name='Utiliser les exercices niveau 3')),
                ('ex_lvl3_min', models.IntegerField(default=0, verbose_name="Nombre minimum d'exercices niveau 3")),
                ('ex_lvl3_max', models.IntegerField(default=5, verbose_name="Nombre maximum d'exercices niveau 3")),
                ('equilibrer_par_chapitre', models.BooleanField(default=True, verbose_name='Équilibrer par chapitre')),
                ('chapitres', modelcluster.fields.ParentalManyToManyField(to='referentiel.chapitre', verbose_name='Chapitres')),
                ('niveau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='referentiel.niveau', verbose_name='Niveau')),
            ],
            options={
                'verbose_name': 'Générateur de devoir surveillé',
                'verbose_name_plural': 'Générateurs de devoirs surveillés',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SerieGeneratorPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('titre', models.CharField(default="Série d'exercices", max_length=200, verbose_name='Titre de la série')),
                ('sous_titre_1', models.CharField(blank=True, max_length=200, verbose_name='Sous-titre 1 (chapitres/thèmes)')),
                ('sous_titre_2', models.CharField(blank=True, max_length=200, verbose_name='Sous-titre 2')),
                ('nb_qcm', models.IntegerField(default=0, verbose_name='Nombre de QCM')),
                ('nb_fc', models.IntegerField(default=0, verbose_name='Nombre de questions-réponses')),
                ('nb_ex_lvl1', models.IntegerField(default=0, verbose_name="Nombre d'exercices niveau 1")),
                ('nb_ex_lvl2', models.IntegerField(default=0, verbose_name="Nombre d'exercices niveau 2")),
                ('nb_ex_lvl3', models.IntegerField(default=0, verbose_name="Nombre d'exercices niveau 3")),
                ('equilibrer_par_chapitre', models.BooleanField(default=True, verbose_name='Équilibrer par chapitre')),
                ('chapitres', modelcluster.fields.ParentalManyToManyField(to='referentiel.chapitre', verbose_name='Chapitres')),
                ('niveau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='referentiel.niveau', verbose_name='Niveau')),
            ],
            options={
                'verbose_name': "Générateur de série d'exercices",
                'verbose_name_plural': "Générateurs de séries d'exercices",
            },
            bases=('wagtailcore.page',),
        ),
    ]
