# Generated by Django 5.2.5 on 2025-09-02 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateurs', '0001_initial'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateursHubPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', models.TextField(blank=True, help_text="Texte d'introduction pour les générateurs", verbose_name='Introduction')),
            ],
            options={
                'verbose_name': 'Hub des générateurs',
                'verbose_name_plural': 'Hubs des générateurs',
            },
            bases=('wagtailcore.page',),
        ),
    ]
